### ISSUE TITLE
Add app screenshots to readme

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#12]
Something like [this](https://github.com/shopyo/shopyo/tree/7e12485330cb4743ed6f3009358efca455618537)  

Run the app and take screenshots

Join the [shopyo server](https://discord.gg/k37Ef6w) for more help!

**Comment by mayank-kr** [comment]
Hey, I would like to contribute, can you please assign this issue to me.

**Comment by Abdur-rahmaanJ** [comment]
Done, join the [server](https://discord.gg/k37Ef6w) if you are stuck!

**Comment by MercheLorenzo** [comment]
Hello!
I am interested in working on this issue. Could I?
Thank you so much!

**Comment by Abdur-rahmaanJ** [comment]
@MercheLorenzo not yet ... let @mayank-kr work on it

**Comment by dozykeys** [comment]
@Abdur-rahmaanJ Is @MercheLorenzo  done now or do i take it up?

**Comment by Abdur-rahmaanJ** [comment]
@dozykeys Mayank was still working on it today ...

**Comment by vickywane** [comment]
Hi @Abdur-rahmaanJ , 

Any update on this?

**Comment by Abdur-rahmaanJ** [comment]
@dozykeys feel free to take it up!

**Comment by dozykeys** [comment]
@Abdur-rahmaanJ thanks for the opportunity. I appreciate and will commence right away

**Comment by dozykeys** [comment]
@Abdur-rahmaanJ i made an PR. Thanks for the opportunity once more
