### ISSUE TITLE
Handle if name too long in POS

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#25]

**Comment by Abdur-rahmaanJ** [comment]
@many-fac3d-g0d

**Comment by dozykeys** [comment]
has this been taken or do i take it up? i may need some description

**Comment by Abdur-rahmaanJ** [comment]
@dozykeys @many-fac3d-g0d was to work on it, lets wait to see what he says for one day

**Comment by many-fac3d-g0d** [comment]
@Abdur-rahmaanJ I'm working on dis, will raise the PR by today

**Comment by Abdur-rahmaanJ** [comment]
Great!

**Comment by Abdur-rahmaanJ** [comment]
@dozykeys try pagination for non-logged in users

**Comment by dozykeys** [comment]
@Abdur-rahmaanJ i currently do not have access to my laptop.Maybe someone else could take it up

**Comment by Abdur-rahmaanJ** [comment]
@dozykeys Oh was an upcoming issue dont worry

**Comment by dozykeys** [comment]
oh! fine @Abdur-rahmaanJ

**Comment by many-fac3d-g0d** [comment]
@Abdur-rahmaanJ PR #27 made for this issue. After fix, the product name handling will be like below,

![chrome_b2WndVRZka](https://user-images.githubusercontent.com/54078651/139311725-f4381f2c-c6f1-4be2-83a9-843768b27f20.png)
