### ISSUE TITLE
Fix the POS

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#36]
The point of sales is broken. The aim of this issue is to fix it.

**Comment by AishwaryaChat** [comment]
@Abdur-rahmaanJ  can I please get more info about this issue, this will be my first ever open source github contribution.

**Comment by Abdur-rahmaanJ** [comment]
@AishwaryaChat 

1. Read the readme to set up the project, ask on discord if you are stuck
2. Go to /dashboard and select poiny of sales
3. There are 2 issues that you will observe like 1. the pos interface is broken and 2. the input button has errors. For 1. onlh html fix is needed

**Comment by Abdur-rahmaanJ** [comment]
@AishwaryaChat Any blocker, we are here to help

**Comment by Westsi** [comment]
I can try to fix this.

**Comment by Abdur-rahmaanJ** [comment]
@Westsi cool, anything, join the discord!

**Comment by Westsi** [comment]
great!

**Comment by Westsi** [comment]
Done!
