### ISSUE TITLE
Point of sale ui broken after switch to bootstrap5

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#4]
Join our discord: https://discord.gg/k37Ef6w and tag @ appinv if you want more help with this issue

**Comment by apelnar0517** [comment]
@Abdur-rahmaanJ  Is this issue still open? I'll claim it if so

**Comment by Abdur-rahmaanJ** [comment]
@apelnar0517 Cool any question, ask on discord. After app set up go to dashboard -> point of sale

**Comment by apelnar0517** [comment]
@Abdur-rahmaanJ If someone else would like to take this issue, that'd be fine. I've tried a few times to get it up and running locally, but keep getting an error that "flask_mailman" is not installed. I've tried re-installing Flask but haven't had much luck with it.

**Comment by Abdur-rahmaanJ** [comment]
@apelnar0517 wait a bit i setup proper instructions

**Comment by apelnar0517** [comment]
@Abdur-rahmaanJ The instructions are fine. I'm wondering if it's something locally I have setup that isn't jiving. I could try blowing it away and setting it up again when I get home.

**Comment by Abdur-rahmaanJ** [comment]
@apelnar0517 Flask-mailman is a library that should be installed if you installed the requirements

**Comment by Abdur-rahmaanJ** [comment]
@apelnar0517 See new instructions

**Comment by Abdur-rahmaanJ** [comment]
@apelnar0517 Just checking

**Comment by apelnar0517** [comment]
@Abdur-rahmaanJ I'm going to un-assign myself. I still cannot get this to run on my machine.

**Comment by Abdur-rahmaanJ** [comment]
@apelnar0517 very weird ... we've got people who run it. Anyways next time ^^

**Comment by many-fac3d-g0d** [comment]
@Abdur-rahmaanJ  or @appinv I want to take dis issue. Couldn't join the discord chat. Would be great if I could more info on dis issue.

**Comment by Abdur-rahmaanJ** [comment]
@many-fac3d-g0d ok 👍

**Comment by many-fac3d-g0d** [comment]
@appinv or @Abdur-rahmaanJ PR #23 made, pls review.
