### ISSUE TITLE
[Minor edit] Change show to hide

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#44]
On [this](https://github.com/shopyo/shopcube/blob/51bf52dc76c505cf5c45d3836c300d6eb8d0acdf/src/shopcube/modules/box__bizhelp/appointment/info.json#L3) line, change `show` to `hide`.

If you need help:
[![Discord](https://img.shields.io/badge/chat%20on-discord-green.svg)](https://discord.gg/k37Ef6w)

After merge, just add your info to [CONTRIBUTORS.md](https://github.com/shopyo/shopcube/blob/dev/CONTRIBUTORS.md)

**Comment by bensonOSei** [comment]
Hello... I'd like to work on this

**Comment by Abdur-rahmaanJ** [comment]
@bensonOSei Added!
