### ISSUE TITLE
Add logo upload for site

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#49]
Currently we are using a generic logo. Allow users to upload their own site logo. Default to default logo if not changed logo.

**Comment by ang-neeson** [comment]
Hello @Abdur-rahmaanJ  I would like to work on this issue! Can you please elaborate more on what you are referring to by 'site logo'. 

Is this the user logo on the top-right hand corner where you click on to login?

**Comment by Abdur-rahmaanJ** [comment]
@ang-neeson We need a central way to change all logo appearances. Logo is the green one which appears by default.

**Comment by amanycodes** [comment]
Hey can you please assign me this issue under the label of hacktoberfest. I would love to work on this issue.

**Comment by Abdur-rahmaanJ** [comment]
@amanycodes Still want to work on this?
