### ISSUE TITLE
Deploy app to Python anywhere for demo

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#5]
Join our discord https://discord.gg/k37Ef6w and tag @ appinv for more info

**Comment by shrutinisal** [comment]
Hi, Can you assign this issue to me so I can try open source/hacktoberfest for the first time? :) I'm a software developer student.

**Comment by Abdur-rahmaanJ** [comment]
Assigned, join the server and ping me

**Comment by vickywane** [comment]
@Abdur-rahmaanJ is @shrutinisal still working on this?

I'd like to work on it if he is not

**Comment by Abdur-rahmaanJ** [comment]
@vickywane can you join the discord and ping me?

**Comment by vickywane** [comment]
@Abdur-rahmaanJ I've done that. 

Check your discord DM.

**Comment by vickywane** [comment]
I have the app running on pythonanywhere [here](http://vickywane.pythonanywhere.com/shop/home). 

How do i proceed?

**Comment by vickywane** [comment]
I have opened this [pull request](https://github.com/shopyo/ShopCube/pull/19) to fix this issue.

**Comment by Abdur-rahmaanJ** [comment]
@vickywane Feel free to star the repo to support it!
