### ISSUE TITLE
[Minor edit] Remove printing of data (2)

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#54]
On [this](https://github.com/shopyo/shopcube/blob/e559a105d273cc9331d9b24811b6b1857796750a/src/shopcube/modules/box__ecommerce/customer/view.py#L47-L47) line, remove the complete line.

If you need help:
[![Discord](https://img.shields.io/badge/chat%20on-discord-green.svg)](https://discord.gg/k37Ef6w)

After merge, just add your info to [CONTRIBUTORS.md](https://github.com/shopyo/shopcube/blob/dev/CONTRIBUTORS.md)

**Comment by frantic-dev** [comment]
Can I work on this ?

**Comment by Abdur-rahmaanJ** [comment]
@frantic-dev Yes!
