### ISSUE TITLE
[Minor edit] Fix url redirection (1)

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#56]
See this warning:
https://github.com/shopyo/shopcube/security/code-scanning/19

Fix it by

```python
from shopyo.api.security import get_safe_redirect

...

    return redirect(get_safe_redirect(next_url))

```

If you need help:
[![Discord](https://img.shields.io/badge/chat%20on-discord-green.svg)](https://discord.gg/k37Ef6w)

After merge, just add your info to [CONTRIBUTORS.md](https://github.com/shopyo/shopcube/blob/dev/CONTRIBUTORS.md)

**Comment by yemiOdetola** [comment]
Hi @Abdur-rahmaanJ, I'll like to work on this... Can I get more details on what needs to be done?

*This is my first OS contribution.

**Comment by Abdur-rahmaanJ** [comment]
@yemiOdetola Join the discord please [here](https://discord.gg/k37Ef6w), we'll guide you!
