### ISSUE TITLE
[Minor edit] Fix url redirection (2)

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#57]
See this warning:
https://github.com/shopyo/shopcube/security/code-scanning/18

Fix it by

```python
from shopyo.api.security import get_safe_redirect

...

    return redirect(get_safe_redirect(next_url))

```

If you need help:
[![Discord](https://img.shields.io/badge/chat%20on-discord-green.svg)](https://discord.gg/k37Ef6w)

After merge, just add your info to [CONTRIBUTORS.md](https://github.com/shopyo/shopcube/blob/dev/CONTRIBUTORS.md)

**Comment by annavordou** [comment]
I'm interested in working on this isssue. Could you kindly provide some more information?

**Comment by Abdur-rahmaanJ** [comment]
@annavordou Just replace `return redirect()`  from [this line](https://github.com/shopyo/shopcube/blob/b3c9992d08fe03e50dd241f41a9ff7084afbe576/src/shopcube/modules/box__ecommerce/shop/view.py#L458) to `return redirect(get_safe_redirect(next_url))`
