### ISSUE TITLE
Beautify readme!

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#6]
Clone, run and explore the app and write a beautiful readme to encourage people to contribute and use the app

Join our discord https://discord.gg/k37Ef6w and tag @ appinv for more info

**Comment by ssurbhi09** [comment]
Can I change the font!

**Comment by Abdur-rahmaanJ** [comment]
@ssurbhi09 it includes more than changing the font. Try reading this first:
https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/

**Comment by ghost** [comment]
can i work on this?

**Comment by Abdur-rahmaanJ** [comment]
@Devtinator if by tomorrow @ssurbhi09 does not reply, feel free to pr

**Comment by ghost** [comment]
ok

**Comment by daking24** [comment]
Hello, how do I contribute
