### ISSUE TITLE
Feat: Display number of products for product category

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#63]
![products_page](https://user-images.githubusercontent.com/22630684/195496029-fb076427-64c7-416e-9d29-2f69c3a69206.png)

Display `products (20)` instead of `products`

**Comment by Abdur-rahmaanJ** [comment]
Join the [discord](https://discord.gg/k37Ef6w) for any question, help getting started and clarifications!

**Comment by 90r1ll4** [comment]
@Abdur-rahmaanJ can you assign this to me ?

**Comment by Abdur-rahmaanJ** [comment]
Done!

**Comment by 90r1ll4** [comment]
@Abdur-rahmaanJ can you tell me the file name to work on ?

**Comment by Abdur-rahmaanJ** [comment]
@90r1ll4 here 

https://github.com/shopyo/shopcube/blob/dev/src/shopcube/modules/box__ecommerce/category/templates/category/dashboard.html

**Comment by Abdur-rahmaanJ** [comment]
@90r1ll4 Any progress?

**Comment by 90r1ll4** [comment]
@Abdur-rahmaanJ sorry cannot figure it out how to produce total count

**Comment by Abdur-rahmaanJ** [comment]
@90r1ll4 Join the Discord, will guide you step by step. This is a simple issue ^^

**Comment by 90r1ll4** [comment]
@Abdur-rahmaanJ  PR  raised kindly check

**Comment by Abdur-rahmaanJ** [comment]
@90r1ll4 Cool!
