### ISSUE TITLE
Feat: Display number of products for product subcategory

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#64]
![subcateg_pag](https://user-images.githubusercontent.com/22630684/195496277-02b22fb6-702d-4c1b-9d81-b81c41078613.png)

Display `products (20)` instead of `products`

**Comment by najeebkp** [comment]
Hey @Abdur-rahmaanJ  please assign this to me

**Comment by Abdur-rahmaanJ** [comment]
Ok!

Join the [discord](https://discord.gg/k37Ef6w) for any question, help getting started and clarifications!

**Comment by najeebkp** [comment]
oh sorry. i thought its a react project.

**Comment by MatejCech20** [comment]
Hello @Abdur-rahmaanJ please assign this to me !

**Comment by Abdur-rahmaanJ** [comment]
@MatejCech20 Done!

**Comment by Abdur-rahmaanJ** [comment]
It's inside product module templates

**Comment by MatejCech20** [comment]
Hello @Abdur-rahmaanJ, can you check pull request ?
