### ISSUE TITLE
Logo wanted

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/shopcube#7]
We want a logo for the project!

Join our discord https://discord.gg/k37Ef6w and tag @ appinv for more info

**Comment by innatepanda** [comment]
Can I please work on this for 24hours?

**Comment by Abdur-rahmaanJ** [comment]
@innatepanda ok ✅

**Comment by innatepanda** [comment]
Can you please share screenshots of the work?

**Comment by Abdur-rahmaanJ** [comment]
@innatepanda https://github.com/shopyo/shopyo/tree/ee3ba17b919fab78395f923ebbef0857790aaf1d


see end of readme

**Comment by innatepanda** [comment]
Thank you.

**Comment by VaithiSniper** [comment]
Hi. If this issue is still open, can I work on it?

**Comment by bharmalh** [comment]
I know graphics design and can design a clean simple logo. Kindly allow me to work on this.

**Comment by Abdur-rahmaanJ** [comment]
@VaithiSniper @bharmalh anyone who prs first

**Comment by VaithiSniper** [comment]
Okay

**Comment by VaithiSniper** [comment]
https://github.com/shopyo/ShopCube/pull/8#issue-1022078458
I've made a PR, please review it. If you need it in different resolutions or anything else, please let me know.

**Comment by VaithiSniper** [comment]
https://github.com/shopyo/ShopCube/pull/9#issue-1022896554
I've made a PR for the same. Check and lemme know. :D
